/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAssistantRouteImport } from './routes/_authenticated/assistant'
import { Route as AuthenticatedClinicRouteImport } from './routes/_authenticated/clinic'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedExecutionRouteImport } from './routes/_authenticated/execution'
import { Route as AuthenticatedFollowUpsRouteImport } from './routes/_authenticated/follow-ups'
import { Route as AuthenticatedLabRouteImport } from './routes/_authenticated/lab'
import { Route as AuthenticatedReceptionRouteImport } from './routes/_authenticated/reception'
import { Route as ApiComplianceJudgeRouteImport } from './routes/api/compliance-judge'
import { Route as ApiCopilotRouteImport } from './routes/api/copilot'
import { Route as ApiOpsReportRouteImport } from './routes/api/ops-report'
import { Route as ApiPatientSummaryRouteImport } from './routes/api/patient-summary'
import { Route as MyChecklistIdRouteImport } from './routes/my-checklist.$id'
import { Route as AuthenticatedPatientsIndexRouteImport } from './routes/_authenticated/patients.index'
import { Route as AuthenticatedPatientsIdRouteImport } from './routes/_authenticated/patients.$id'
import { Route as AuthenticatedVisitsIdRouteImport } from './routes/_authenticated/visits.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssistantRoute = AuthenticatedAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClinicRoute = AuthenticatedClinicRouteImport.update({
  id: '/clinic',
  path: '/clinic',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExecutionRoute = AuthenticatedExecutionRouteImport.update({
  id: '/execution',
  path: '/execution',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFollowUpsRoute = AuthenticatedFollowUpsRouteImport.update({
  id: '/follow-ups',
  path: '/follow-ups',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLabRoute = AuthenticatedLabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReceptionRoute = AuthenticatedReceptionRouteImport.update({
  id: '/reception',
  path: '/reception',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiComplianceJudgeRoute = ApiComplianceJudgeRouteImport.update({
  id: '/api/compliance-judge',
  path: '/api/compliance-judge',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCopilotRoute = ApiCopilotRouteImport.update({
  id: '/api/copilot',
  path: '/api/copilot',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpsReportRoute = ApiOpsReportRouteImport.update({
  id: '/api/ops-report',
  path: '/api/ops-report',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPatientSummaryRoute = ApiPatientSummaryRouteImport.update({
  id: '/api/patient-summary',
  path: '/api/patient-summary',
  getParentRoute: () => rootRouteImport,
} as any)
const MyChecklistIdRoute = MyChecklistIdRouteImport.update({
  id: '/my-checklist/$id',
  path: '/my-checklist/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPatientsIndexRoute =
  AuthenticatedPatientsIndexRouteImport.update({
    id: '/patients/',
    path: '/patients/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPatientsIdRoute = AuthenticatedPatientsIdRouteImport.update({
  id: '/patients/$id',
  path: '/patients/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVisitsIdRoute = AuthenticatedVisitsIdRouteImport.update({
  id: '/visits/$id',
  path: '/visits/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/assistant': typeof AuthenticatedAssistantRoute
  '/clinic': typeof AuthenticatedClinicRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/execution': typeof AuthenticatedExecutionRoute
  '/follow-ups': typeof AuthenticatedFollowUpsRoute
  '/lab': typeof AuthenticatedLabRoute
  '/reception': typeof AuthenticatedReceptionRoute
  '/api/compliance-judge': typeof ApiComplianceJudgeRoute
  '/api/copilot': typeof ApiCopilotRoute
  '/api/ops-report': typeof ApiOpsReportRoute
  '/api/patient-summary': typeof ApiPatientSummaryRoute
  '/my-checklist/$id': typeof MyChecklistIdRoute
  '/patients/$id': typeof AuthenticatedPatientsIdRoute
  '/visits/$id': typeof AuthenticatedVisitsIdRoute
  '/patients/': typeof AuthenticatedPatientsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/assistant': typeof AuthenticatedAssistantRoute
  '/clinic': typeof AuthenticatedClinicRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/execution': typeof AuthenticatedExecutionRoute
  '/follow-ups': typeof AuthenticatedFollowUpsRoute
  '/lab': typeof AuthenticatedLabRoute
  '/reception': typeof AuthenticatedReceptionRoute
  '/api/compliance-judge': typeof ApiComplianceJudgeRoute
  '/api/copilot': typeof ApiCopilotRoute
  '/api/ops-report': typeof ApiOpsReportRoute
  '/api/patient-summary': typeof ApiPatientSummaryRoute
  '/my-checklist/$id': typeof MyChecklistIdRoute
  '/patients/$id': typeof AuthenticatedPatientsIdRoute
  '/visits/$id': typeof AuthenticatedVisitsIdRoute
  '/patients': typeof AuthenticatedPatientsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/assistant': typeof AuthenticatedAssistantRoute
  '/_authenticated/clinic': typeof AuthenticatedClinicRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/execution': typeof AuthenticatedExecutionRoute
  '/_authenticated/follow-ups': typeof AuthenticatedFollowUpsRoute
  '/_authenticated/lab': typeof AuthenticatedLabRoute
  '/_authenticated/reception': typeof AuthenticatedReceptionRoute
  '/api/compliance-judge': typeof ApiComplianceJudgeRoute
  '/api/copilot': typeof ApiCopilotRoute
  '/api/ops-report': typeof ApiOpsReportRoute
  '/api/patient-summary': typeof ApiPatientSummaryRoute
  '/my-checklist/$id': typeof MyChecklistIdRoute
  '/_authenticated/patients/$id': typeof AuthenticatedPatientsIdRoute
  '/_authenticated/visits/$id': typeof AuthenticatedVisitsIdRoute
  '/_authenticated/patients/': typeof AuthenticatedPatientsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/assistant'
    | '/clinic'
    | '/dashboard'
    | '/execution'
    | '/follow-ups'
    | '/lab'
    | '/reception'
    | '/api/compliance-judge'
    | '/api/copilot'
    | '/api/ops-report'
    | '/api/patient-summary'
    | '/my-checklist/$id'
    | '/patients/$id'
    | '/visits/$id'
    | '/patients/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/assistant'
    | '/clinic'
    | '/dashboard'
    | '/execution'
    | '/follow-ups'
    | '/lab'
    | '/reception'
    | '/api/compliance-judge'
    | '/api/copilot'
    | '/api/ops-report'
    | '/api/patient-summary'
    | '/my-checklist/$id'
    | '/patients/$id'
    | '/visits/$id'
    | '/patients'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/assistant'
    | '/_authenticated/clinic'
    | '/_authenticated/dashboard'
    | '/_authenticated/execution'
    | '/_authenticated/follow-ups'
    | '/_authenticated/lab'
    | '/_authenticated/reception'
    | '/api/compliance-judge'
    | '/api/copilot'
    | '/api/ops-report'
    | '/api/patient-summary'
    | '/my-checklist/$id'
    | '/_authenticated/patients/$id'
    | '/_authenticated/visits/$id'
    | '/_authenticated/patients/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiComplianceJudgeRoute: typeof ApiComplianceJudgeRoute
  ApiCopilotRoute: typeof ApiCopilotRoute
  ApiOpsReportRoute: typeof ApiOpsReportRoute
  ApiPatientSummaryRoute: typeof ApiPatientSummaryRoute
  MyChecklistIdRoute: typeof MyChecklistIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assistant': {
      id: '/_authenticated/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AuthenticatedAssistantRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clinic': {
      id: '/_authenticated/clinic'
      path: '/clinic'
      fullPath: '/clinic'
      preLoaderRoute: typeof AuthenticatedClinicRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/execution': {
      id: '/_authenticated/execution'
      path: '/execution'
      fullPath: '/execution'
      preLoaderRoute: typeof AuthenticatedExecutionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/follow-ups': {
      id: '/_authenticated/follow-ups'
      path: '/follow-ups'
      fullPath: '/follow-ups'
      preLoaderRoute: typeof AuthenticatedFollowUpsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lab': {
      id: '/_authenticated/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof AuthenticatedLabRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reception': {
      id: '/_authenticated/reception'
      path: '/reception'
      fullPath: '/reception'
      preLoaderRoute: typeof AuthenticatedReceptionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/compliance-judge': {
      id: '/api/compliance-judge'
      path: '/api/compliance-judge'
      fullPath: '/api/compliance-judge'
      preLoaderRoute: typeof ApiComplianceJudgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/copilot': {
      id: '/api/copilot'
      path: '/api/copilot'
      fullPath: '/api/copilot'
      preLoaderRoute: typeof ApiCopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ops-report': {
      id: '/api/ops-report'
      path: '/api/ops-report'
      fullPath: '/api/ops-report'
      preLoaderRoute: typeof ApiOpsReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/patient-summary': {
      id: '/api/patient-summary'
      path: '/api/patient-summary'
      fullPath: '/api/patient-summary'
      preLoaderRoute: typeof ApiPatientSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-checklist/$id': {
      id: '/my-checklist/$id'
      path: '/my-checklist/$id'
      fullPath: '/my-checklist/$id'
      preLoaderRoute: typeof MyChecklistIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/patients/': {
      id: '/_authenticated/patients/'
      path: '/patients'
      fullPath: '/patients/'
      preLoaderRoute: typeof AuthenticatedPatientsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/patients/$id': {
      id: '/_authenticated/patients/$id'
      path: '/patients/$id'
      fullPath: '/patients/$id'
      preLoaderRoute: typeof AuthenticatedPatientsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/visits/$id': {
      id: '/_authenticated/visits/$id'
      path: '/visits/$id'
      fullPath: '/visits/$id'
      preLoaderRoute: typeof AuthenticatedVisitsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAssistantRoute: typeof AuthenticatedAssistantRoute
  AuthenticatedClinicRoute: typeof AuthenticatedClinicRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedExecutionRoute: typeof AuthenticatedExecutionRoute
  AuthenticatedFollowUpsRoute: typeof AuthenticatedFollowUpsRoute
  AuthenticatedLabRoute: typeof AuthenticatedLabRoute
  AuthenticatedReceptionRoute: typeof AuthenticatedReceptionRoute
  AuthenticatedPatientsIdRoute: typeof AuthenticatedPatientsIdRoute
  AuthenticatedVisitsIdRoute: typeof AuthenticatedVisitsIdRoute
  AuthenticatedPatientsIndexRoute: typeof AuthenticatedPatientsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAssistantRoute: AuthenticatedAssistantRoute,
  AuthenticatedClinicRoute: AuthenticatedClinicRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedExecutionRoute: AuthenticatedExecutionRoute,
  AuthenticatedFollowUpsRoute: AuthenticatedFollowUpsRoute,
  AuthenticatedLabRoute: AuthenticatedLabRoute,
  AuthenticatedReceptionRoute: AuthenticatedReceptionRoute,
  AuthenticatedPatientsIdRoute: AuthenticatedPatientsIdRoute,
  AuthenticatedVisitsIdRoute: AuthenticatedVisitsIdRoute,
  AuthenticatedPatientsIndexRoute: AuthenticatedPatientsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiComplianceJudgeRoute: ApiComplianceJudgeRoute,
  ApiCopilotRoute: ApiCopilotRoute,
  ApiOpsReportRoute: ApiOpsReportRoute,
  ApiPatientSummaryRoute: ApiPatientSummaryRoute,
  MyChecklistIdRoute: MyChecklistIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
