-- Phase 03 — seed dental_snomed_whitelist (trích từ 6 module + mã nha cơ bản).
-- Đã loại mã bệnh nền tham chiếu (Diabetes 44054006, thai kỳ, rối loạn đông máu, suy giảm miễn dịch — thuộc Lane1).
DELETE FROM public.dental_snomed_whitelist;
INSERT INTO public.dental_snomed_whitelist (code, label, source_module, kind) VALUES
  ('1089981000119106', 'Lesion of oral mucosa (disorder)', 'oral_cancer', 'condition'),
  ('109500001', 'Malocclusion, Angle class I (disorder)', 'orthodontics', 'condition'),
  ('109501002', 'Malocclusion, Angle class II (disorder)', 'orthodontics', 'condition'),
  ('109504005', 'Malocclusion, Angle class III (disorder)', 'orthodontics', 'condition'),
  ('109570000', 'Missing tooth', 'core', 'condition'),
  ('109600005', 'Irreversible pulpitis (disorder)', 'endodontics', 'condition'),
  ('109602002', 'Acute apical abscess (disorder)', 'endodontics', 'condition'),
  ('109603007', 'Chronic apical abscess (disorder)', 'endodontics', 'condition'),
  ('109629007', 'Periodontal pocket (disorder)', 'periodontal_disease', 'condition'),
  ('109661006', 'Temporomandibular joint disc displacement, without reduction (disorder)', 'tmj_disorder', 'condition'),
  ('109662004', 'Temporomandibular joint disc displacement, with reduction (disorder)', 'tmj_disorder', 'condition'),
  ('11347004', 'Modified radical neck dissection (procedure)', 'oral_cancer', 'procedure'),
  ('1149448005', 'American Academy of Periodontology and European Federation of Periodontology 2017 Classification of Periodontal and Peri-implant Diseases and Conditions generalized periodontitis Stage 4 Grade C (disorder)', 'periodontal_disease', 'condition'),
  ('1149449002', 'American Academy of Periodontology and European Federation of Periodontology 2017 Classification of Periodontal and Peri-implant Diseases and Conditions generalized periodontitis Stage 4 Grade B (disorder)', 'periodontal_disease', 'condition'),
  ('1149450002', 'American Academy of Periodontology and European Federation of Periodontology 2017 Classification of Periodontal and Peri-implant Diseases and Conditions generalized periodontitis Stage 4 Grade A (disorder)', 'periodontal_disease', 'condition'),
  ('1149451003', 'American Academy of Periodontology and European Federation of Periodontology 2017 Classification of Periodontal and Peri-implant Diseases and Conditions generalized periodontitis Stage 3 Grade B (disorder)', 'periodontal_disease', 'condition'),
  ('1149452005', 'American Academy of Periodontology and European Federation of Periodontology 2017 Classification of Periodontal and Peri-implant Diseases and Conditions generalized periodontitis Stage 3 Grade C (disorder)', 'periodontal_disease', 'condition'),
  ('1149453000', 'American Academy of Periodontology and European Federation of Periodontology 2017 Classification of Periodontal and Peri-implant Diseases and Conditions generalized periodontitis Stage 3 Grade A (disorder)', 'periodontal_disease', 'condition'),
  ('1149455007', 'American Academy of Periodontology and European Federation of Periodontology 2017 Classification of Periodontal and Peri-implant Diseases and Conditions generalized periodontitis Stage 2 Grade C (disorder)', 'periodontal_disease', 'condition'),
  ('1149456008', 'American Academy of Periodontology and European Federation of Periodontology 2017 Classification of Periodontal and Peri-implant Diseases and Conditions generalized periodontitis Stage 2 Grade B (disorder)', 'periodontal_disease', 'condition'),
  ('1149457004', 'American Academy of Periodontology and European Federation of Periodontology 2017 Classification of Periodontal and Peri-implant Diseases and Conditions generalized periodontitis Stage 2 Grade A (disorder)', 'periodontal_disease', 'condition'),
  ('1149458009', 'American Academy of Periodontology and European Federation of Periodontology 2017 Classification of Periodontal and Peri-implant Diseases and Conditions generalized periodontitis Stage 1 Grade C (disorder)', 'periodontal_disease', 'condition'),
  ('1149459001', 'American Academy of Periodontology and European Federation of Periodontology 2017 Classification of Periodontal and Peri-implant Diseases and Conditions generalized periodontitis Stage 1 Grade B (disorder)', 'periodontal_disease', 'condition'),
  ('1149460006', 'American Academy of Periodontology and European Federation of Periodontology 2017 Classification of Periodontal and Peri-implant Diseases and Conditions generalized periodontitis Stage 1 Grade A (disorder)', 'periodontal_disease', 'condition'),
  ('115006', 'Removable appliance therapy (procedure)', 'orthodontics', 'procedure'),
  ('1156981009', 'Implantation of dental endosseous implant (procedure)', 'dental_implant', 'procedure'),
  ('117031000119109', 'Biological failure of dental implant after osseointegration (disorder)', 'dental_implant', 'condition'),
  ('1172772005', 'Excision of apex of root of tooth (procedure)', 'endodontics', 'procedure'),
  ('122452007', 'Comprehensive orthodontic treatment (procedure)', 'orthodontics', 'procedure'),
  ('1259237005', 'Recurrent malignant neoplasm (disorder)', 'oral_cancer', 'condition'),
  ('1264277001', 'Treatment of root canal of tooth (procedure)', 'endodontics', 'procedure'),
  ('1285470001', 'Fitting of dental crown to dental implant (procedure)', 'dental_implant', 'procedure'),
  ('133899007', 'Postoperative care (regime/therapy)', 'dental_implant', 'procedure'),
  ('133918004', 'Comfort measures (regime/therapy)', 'oral_cancer', 'procedure'),
  ('1340164000', 'Revision of treatment of root canal of tooth (procedure)', 'endodontics', 'procedure'),
  ('1340197004', 'Preparation of root canal of tooth and insertion of preformed post (procedure)', 'endodontics', 'procedure'),
  ('16177004', 'Orthodontic procedure (procedure)', 'orthodontics', 'procedure'),
  ('173291009', 'Simple extraction of tooth (procedure)', 'endodontics', 'procedure'),
  ('173316001', 'Removal of orthodontic appliance (procedure)', 'orthodontics', 'procedure'),
  ('173333008', 'Removal of accretion from tooth using dental scaler (procedure)', 'periodontal_disease', 'procedure'),
  ('173364005', 'Biopsy of lesion of tongue (procedure)', 'oral_cancer', 'procedure'),
  ('178493006', 'Alveolar bone graft (procedure)', 'dental_implant', 'procedure'),
  ('182964004', 'Terminal care (regime/therapy)', 'oral_cancer', 'procedure'),
  ('21459002', 'Loss of teeth due to local periodontal disease (disorder)', 'periodontal_disease', 'condition'),
  ('231326006', 'Intrapulpal anesthesia (procedure)', 'endodontics', 'procedure'),
  ('234246002', 'Selective neck dissection of cervical lymph nodes (procedure)', 'oral_cancer', 'procedure'),
  ('234675004', 'Periapical curettage of tooth root (procedure)', 'endodontics', 'procedure'),
  ('234678002', 'Debridement of periodontium (procedure)', 'periodontal_disease', 'procedure'),
  ('234682000', 'Modified Widman flap (procedure)', 'periodontal_disease', 'procedure'),
  ('234687006', 'Grafting of periodontal bone defect (procedure)', 'periodontal_disease', 'procedure'),
  ('234699004', 'Planing of root of tooth (procedure)', 'periodontal_disease', 'procedure'),
  ('234700003', 'Cavity preparation of tooth - pulpal access (procedure)', 'endodontics', 'procedure'),
  ('234707000', 'Root canal preparation (procedure)', 'endodontics', 'procedure'),
  ('234708005', 'Irrigation of root canal (procedure)', 'endodontics', 'procedure'),
  ('234712004', 'Root canal obturation (procedure)', 'endodontics', 'procedure'),
  ('234713005', 'Dental fluoride treatment', 'core', 'procedure'),
  ('234745004', 'Take oral or dental impression (procedure)', 'orthodontics', 'procedure'),
  ('234754001', 'Take impression for orthodontic appliance (procedure)', 'orthodontics', 'procedure'),
  ('234772007', 'Take impression for dental implant (procedure)', 'dental_implant', 'procedure'),
  ('235027002', 'Homogenous oral leukoplakia (disorder)', 'oral_cancer', 'condition'),
  ('235030009', 'Dysplastic oral leukoplakia (disorder)', 'oral_cancer', 'condition'),
  ('240532009', 'Human papillomavirus infection (disorder)', 'oral_cancer', 'condition'),
  ('2406000', 'Periodontic dental consultation and report (procedure)', 'periodontal_disease', 'procedure'),
  ('243072006', 'Cancer education (procedure)', 'oral_cancer', 'procedure'),
  ('243085009', 'Oral health education (procedure)', 'orthodontics', 'procedure'),
  ('243092004', 'Orthodontic appliance care education (procedure)', 'orthodontics', 'procedure'),
  ('2535006', 'Pulpectomy (procedure)', 'endodontics', 'procedure'),
  ('26284000', 'Ulcer of mouth (disorder)', 'oral_cancer', 'condition'),
  ('265328005', 'Periapical surgery of tooth (procedure)', 'endodontics', 'procedure'),
  ('274788003', 'Examination of gingivae (procedure)', 'periodontal_disease', 'procedure'),
  ('274950005', 'Sleep-related bruxism (disorder)', 'tmj_disorder', 'condition'),
  ('276952000', 'Squamous cell carcinoma of tongue (disorder)', 'oral_cancer', 'condition'),
  ('276954004', 'Squamous cell carcinoma of floor of mouth (disorder)', 'oral_cancer', 'condition'),
  ('284395004', 'Examination of temporomandibular joint (procedure)', 'tmj_disorder', 'procedure'),
  ('304502009', 'Biopsy of mouth (procedure)', 'oral_cancer', 'procedure'),
  ('304995007', 'Modified Widman flap with osseous surgery (procedure)', 'periodontal_disease', 'procedure'),
  ('306988000', 'Attach dental implant superstructure (procedure)', 'dental_implant', 'procedure'),
  ('307502000', 'Squamous cell carcinoma of mouth (disorder)', 'oral_cancer', 'condition'),
  ('34043003', 'Dental consultation and report (procedure)', 'dental_implant', 'procedure'),
  ('37542007', 'Posttreatment stabilization, orthodontic device (procedure)', 'orthodontics', 'procedure'),
  ('3802001', 'Dental application of desensitizing medicament (procedure)', 'endodontics', 'procedure'),
  ('386207004', 'Temporomandibular joint-pain-dysfunction syndrome (disorder)', 'tmj_disorder', 'condition'),
  ('39273001', 'Apical periodontitis (disorder)', 'endodontics', 'condition'),
  ('397791003', 'Drainage of alveolar tooth abscess (procedure)', 'endodontics', 'procedure'),
  ('408957008', 'Chronic pain control management (procedure)', 'oral_cancer', 'procedure'),
  ('41888000', 'Temporomandibular joint disorder (disorder)', 'tmj_disorder', 'condition'),
  ('42123008', 'Type III, moderate periodontitis, moderate to deep pocket therapy (procedure)', 'periodontal_disease', 'procedure'),
  ('423464009', 'Squamous cell carcinoma of oropharynx (disorder)', 'oral_cancer', 'condition'),
  ('42711005', 'Necrosis of the pulp (disorder)', 'endodontics', 'condition'),
  ('4356008', 'Gingival recession (disorder)', 'periodontal_disease', 'condition'),
  ('44095009', 'Removal of dental implant (procedure)', 'dental_implant', 'procedure'),
  ('441799006', 'Intensity modulated radiation therapy (procedure)', 'oral_cancer', 'procedure'),
  ('442437005', 'Failure of osseointegration of dental implant (disorder)', 'dental_implant', 'condition'),
  ('444780001', 'Dental care', 'core', 'procedure'),
  ('448199007', 'Centesis of temporomandibular joint (procedure)', 'tmj_disorder', 'procedure'),
  ('448502003', 'Arthroscopy of temporomandibular joint (procedure)', 'tmj_disorder', 'procedure'),
  ('45080003', 'Gingival flap procedure, including root planing, per quadrant (procedure)', 'periodontal_disease', 'procedure'),
  ('454511000124109', 'Augmentation of maxillary sinus (procedure)', 'dental_implant', 'procedure'),
  ('456191000124101', 'Postoperative care for dental procedure (regime/therapy)', 'endodontics', 'procedure'),
  ('47944004', 'Malocclusion of teeth (disorder)', 'orthodontics', 'condition'),
  ('50271000', 'Dental implant maintenance procedure (procedure)', 'dental_implant', 'procedure'),
  ('5154007', 'Speech therapy (regime/therapy)', 'oral_cancer', 'procedure'),
  ('53075003', 'Dental examination', 'core', 'procedure'),
  ('55656007', 'Fixed appliance therapy (procedure)', 'orthodontics', 'procedure'),
  ('59789006', 'Type I, gingivitis, shallow pocket therapy (procedure)', 'periodontal_disease', 'procedure'),
  ('60883007', 'Personal periodontal care, plaque control education (procedure)', 'periodontal_disease', 'procedure'),
  ('64587006', 'Emergency endodontic procedure (procedure)', 'endodontics', 'procedure'),
  ('66383009', 'Gingivitis (disorder)', 'periodontal_disease', 'condition'),
  ('6732009', 'Type II, early periodontitis, moderate pocket therapy (procedure)', 'periodontal_disease', 'procedure'),
  ('68769000', 'Partial glossectomy (procedure)', 'oral_cancer', 'procedure'),
  ('69299000', 'Erythroplakia of mouth (disorder)', 'oral_cancer', 'condition'),
  ('699422003', 'Dental peri-implantitis (disorder)', 'dental_implant', 'condition'),
  ('699684005', 'Dental peri-implant mucositis (disorder)', 'dental_implant', 'condition'),
  ('703423002', 'Combined chemotherapy and radiation therapy (procedure)', 'oral_cancer', 'procedure'),
  ('71061001', 'Dentoalveolar bone osseous surgery, including flap entry and closure, per quadrant (procedure)', 'periodontal_disease', 'procedure'),
  ('711638008', 'Symptomatic irreversible pulpitis (disorder)', 'endodontics', 'condition'),
  ('71387007', 'Endodontic dental consultation and report (procedure)', 'endodontics', 'procedure'),
  ('718053009', 'Symptomatic periapical periodontitis (disorder)', 'endodontics', 'condition'),
  ('737567002', 'Major surgery care management (procedure)', 'oral_cancer', 'procedure'),
  ('75954006', 'Type IV, advanced periodontitis, deep pocket therapy (procedure)', 'periodontal_disease', 'procedure'),
  ('771343009', 'Measurement of periodontal pocket depth-six areas per tooth exam (procedure)', 'periodontal_disease', 'procedure'),
  ('79321009', 'Application of splint (procedure)', 'tmj_disorder', 'procedure'),
  ('80967001', 'Dental caries', 'core', 'condition'),
  ('81407003', 'Apical granuloma (disorder)', 'endodontics', 'condition'),
  ('81733005', 'Dental surgical procedure (procedure)', 'endodontics', 'procedure'),
  ('82468009', 'Subgingival curettage (procedure)', 'periodontal_disease', 'procedure'),
  ('827137007', 'Guided periodontal tissue regeneration (procedure)', 'periodontal_disease', 'procedure'),
  ('83412009', 'Periodontal abscess (disorder)', 'periodontal_disease', 'condition'),
  ('85357001', 'Excision of lesion of mouth (procedure)', 'oral_cancer', 'procedure'),
  ('89291005', 'Orthodontic dental consultation and report (procedure)', 'orthodontics', 'procedure'),
  ('91251008', 'Physical therapy procedure (regime/therapy)', 'tmj_disorder', 'procedure'),
  ('91943004', 'Arthralgia of temporomandibular joint (disorder)', 'tmj_disorder', 'condition'),
  ('91950000', 'Atrophy of edentulous alveolar ridge (disorder)', 'dental_implant', 'condition'),
  ('93446008', 'Edentulous alveolar ridge (disorder)', 'dental_implant', 'condition')
ON CONFLICT (code) DO NOTHING;
